trigger:
- master
- rel/*

pr:
- master
- rel/*

pool:
  vmImage: vs2017-win2016

variables: 
  BuildConfiguration: Release
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.500'

- task: DotNetCoreCLI@2  
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv
  displayName: Install NBGV tool

- script: nbgv cloud
  displayName: Set Version

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: .\AntiXSS.sln
    arguments: -c $(BuildConfiguration)
  displayName: Build  
  
- powershell: |
    mkdir $(Build.ArtifactStagingDirectory)\Packages
    $version = .\nbgv get-version -f json | ConvertFrom-Json
    dotnet pack .\Microsoft.Security.Application.Encoder\Microsoft.Security.Application.Encoder.csproj --no-build -o $(Build.ArtifactStagingDirectory)\Packages /p:NuspecFile=$($item.FullName) /p:NuspecBasePath=..\ /p:NuspecProperties="version=$($version.NuGetPackageVersion);RepositoryType=git;RepositoryCommit=$($version.GitCommitId);RepositoryUrl=https://github.com/hangy/AntiXSS" 
  displayName: Create packages
  
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: .\Microsoft.Security.Application.Encoder.UnitTests\Microsoft.Security.Application.Encoder.UnitTests.csproj
    arguments: -c $(BuildConfiguration) /p:DebugType=portable
  displayName: Run Tests

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: .\Microsoft.Security.Application.HtmlSanitization.Tests\Microsoft.Security.Application.HtmlSanitization.Tests.csproj
    arguments: -c $(BuildConfiguration) /p:DebugType=portable
  displayName: Run Tests

- task: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)\Packages
    artifactType: container
    artifactName: Packages